name: CI Pipeline

env:
  AWS_REGION: ap-northeast-1
  APP_NAME: my-tsubuyaki-app

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy: # runnerを指定
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source # githubからリポジトリを取得
        uses: actions/checkout@v4

      - name: Set up JDK 21 # JDK21環境を構築 mavenはrunnerに元々含まれてる
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests # testフォルダ以下のJUnitテストコードを実行
        run: mvn clean test

      - name: Upload test reports #テスト結果をartifact保存
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Build WAR # WARファイルを作る
        run: mvn package

      - name: Upload WAR artifact # WARファイルをartifactに保存（使うわけではない）
        uses: actions/upload-artifact@v4
        with:
          name: my-tsubuyaki-app-war
          path: target/${{ env.APP_NAME }}.war
      
      - name: Login to GHCR # GHCRにログイン
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image #dockerイメージを作成（Tomcat10 + redisson  + WAR）。タグは2つ付ける。
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:latest \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ github.run_number }} \
          .

      - name: Push Docker Image # GHCRに2つのタグ名でアップロード
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ github.run_number }}
      
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR # ECRの一時パスワードを取得し、ログインする
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}
          
      - name: Add tag to Image
        run: docker tag ghcr.io/${{ github.repository_owner }}/${{ env.APP_NAME }}:latest ${{ secrets.AWS_ECR_REPO}}/${{ env.APP_NAME }}:latest
        
      - name: Push Docker Imange to ECR
        run: docker push ${{ secrets.AWS_ECR_REPO}}/${{ env.APP_NAME }}:latest
        